### ISSUE TITLE
Compilation error OTP-27 : asmjit/core/virtmem.cpp:288:3: internal compiler error

### ISSUE THREAD

**Issue by crownedgrouse** [erlang/otp#8668]
**Describe the bug**
OTP-27 fail to build with kerl or even manually on 18.04.1-Ubuntu SMP x86_64 GNU/Linux. 

A bug #8065  was already reporting this and state that gcc 8 or above might fix this, but  installing highest deb package gcc ( 8.4.0 ) available does not work for me.
Can OTP team be more precise how to handle the case ?

**To Reproduce**
kerl build 27.0.1 27.0.1  on 18.04.1-Ubuntu SMP x86_64 GNU/Linux with gcc-8.4.0

**Affected versions**
27.0 and 27.0.1

**Additional context**
```
 CXX	obj/x86_64-pc-linux-gnu/opt/jit/asmjit/core/builder.o
 CXX	obj/x86_64-pc-linux-gnu/opt/jit/asmjit/core/zonevector.o
 CXX	obj/x86_64-pc-linux-gnu/opt/jit/asmjit/core/virtmem.o
asmjit/core/virtmem.cpp:288:3: internal compiler error: Erreur de segmentation
   inline long major() const noexcept { return ver[0]; }
   ^~~~~~
```
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.4.0-1ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.4.0 (Ubuntu 8.4.0-1ubuntu1~18.04) 
```

**Comment by crownedgrouse** [comment]
For what it worth, I could compile with gcc  9.4.0 (Ubuntu  20.04.2).
A clear statement in Install procedure and/or configure should warn on minimal gcc version to be used.

**Comment by jhogberg** [comment]
The latest supported version of GCC is 11.x which makes GCC 8.x very old at this point. I think we can't be much clearer than "use a compiler that is actively maintained and file bugs with them if you run into issues." :-/

**Comment by kobalicek** [comment]
Interestingly, AsmJit's CI pipeline tests GCC 7+ and it all works:

  - https://github.com/asmjit/asmjit/actions/runs/9837407605

If there is a trivial fix to this I would not really mind, but it's impossible to verify.
