### ISSUE TITLE
code:ensure_loaded/1 hangs on case-mistaken module 

### ISSUE THREAD

**Issue by sabiwara** [erlang/otp#7725]
**Describe the bug**
`code:ensure_loaded/1` hangs on the second call when the module has a case mistake on MacOS.

**To Reproduce**

With a `'Elixir.Foo'` module defined below, in `erl`:

```erlang
1> code:ensure_loaded('Elixir.FOo').
=ERROR REPORT==== 9-Oct-2023::08:18:48.125215 ===
beam/beam_load.c(180): Error loading module 'Elixir.FOo':
  module name in object code is 'Elixir.Foo'


{error,badfile}
2> code:ensure_loaded('Elixir.FOo').
% ===== hangs forever ====
```

**Expected behavior**

**Affected versions**
OTP 26.1 (works fine on 26.0.2).

**Additional context**

`cat Elixir.Foo.erl`:
```erlang
-module('Elixir.Foo').

-export([bar/0]).

bar() -> bar.
```

**Comment by josevalim** [comment]
I believe it is related to https://github.com/erlang/otp/commit/cb85704d8cc2cef6a4bf44f687a7f69ca4917fd0. If loading fails, we don’t reply with this information. I can send a PR within the next 24 hours.

**Comment by josevalim** [comment]
Note that we can also get stuck when:

1. when trying to load embedded code (#7721)
2. when there is a deadlock inside on_load callback

None of those failures clear the loading queue.

**Comment by josevalim** [comment]
Here is a summary of the possible solutions as I see them.

### 1. Move to the code server

Have the ensure loading operation happen in full in the code server.

Pros: simplest solution

Cons: makes the code server more likely to become a bottleneck (and it is a bottleneck when applications do an interactive cold boot, when running tests, etc)

Number of messages for ensure loading: 2

### 2. Client module loading

Have the ensure loading happen, as much as possible, on the client. This is what we tried on 26.0.

Pros: theoretically, it is the most scalable

Cons: in practice, there were pathological cases that made it slower due to concurrent module loaded

Number of messages for ensure loading: 4

### 3. Client module loading with locking

Have the ensure loading happen on the client, by using the server to create a lock. This is what we have on 26.1.

Pros: Still do some work on the client

Cons: It is the most complex solution and is debatable if the amount of client work is enough to justify it

Number of messages for ensure loading: 4

### 4. Split code server in code server and code loader (**new!**)

I have a new suggestion. If the main concern is the code server being a bottleneck, then we could split the code server in two. The `code_server` keeps its current responsibilities. The new `erts_code_loader` handles the `moddb` and `on_load` callbacks (inspired by `erts_code_purger`).

Pros: Helps refactor and clean up the code, while reducing the odds of being a bottleneck

Cons: There is still a chance of it becoming a bottleneck. Theoretically, we could parallelize the work by creating a pool of code loaders and hashing to them based on the module name. However, we do have APIs that load modules as a group, and then hashing wouldn't work for those.

Number of messages for ensure loading: 4

---

I have some questions:

* How expensive can `erlang:prepare_loading(Mod, Bin)` be in practice?

* Is it necessary for `erlang:finish_loading/1` to happen within a single process? Would concurrent calls to `erlang:finish_loading/1` (potentially with the same module) be an issue?

* What about `erts_code_purger`? It is a separate process but still called through the `code_server`, could we invoke the `erts_code_purger` directly from the client?

**Comment by josevalim** [comment]
I ended up sending a PR with solution #7755, implementing case 3.

I have further ideas on how to optimize the code if it is client based (i.e. we can leverage the code path cache to avoid reading files in the code server altogether), so I preferred to maintain the status quo. The optimizations were not implemented yet, since it is targetting maint.

**Comment by josevalim** [comment]
This has been fixed and can be closed.
