### ISSUE TITLE
OTP 26 writes corrupted messages to stdout in latin1 mode on Windows

### ISSUE THREAD

**Issue by lukaszsamson** [erlang/otp#7838]
**Describe the bug**
Write to `standard_io` in `standard_io_encoding latin1` mode results in corrupted output. This issue affects ElixirLS as in response to corrupted LSP message editors shut down misbehaving language server. Originally reported in https://github.com/elixir-lsp/elixir-ls/issues/1023

**To Reproduce**
1. clone https://github.com/lukaszsamson/otp26-trunc-repro
2. run `test_erlang_big.bat`
3. verify md5 hashes and file sizes of input and output files

Notice that hashes do not match and output file is 2GB instead of 500kB. The contents of the file include repeated input file fragments (or possibly memory dump)

**Expected behavior**
The script should read a binary and write it back to stdout in latin1 mode. Terminal redirection should write it to `out.txt`. The output should be identical to input. MD5 hashes should be equal.

**Affected versions**
OTP 26.1.2

**Additional context**
This is likely another IO related bug introduced in OTP 26. The problem does not exist on *nix. The problem only manifests if file size is greater than some threshold around 500kB.
`test_erlang_small.bat` works correctly on OTP 26.1.2
both `test_erlang_small.sh` and `test_erlang_big.sh` work correctly on *nix on OTP 26.1.2
both `test_erlang_small.bat` and `test_erlang_big.bat` work correctly on OTP 25.3.2.7
`test_erlang_big_no_latin.bat` writes a file having similar size but obviously the file differs as `standard_io` is in `utf8` mode

**Comment by garazdawi** [comment]
Thanks for the report and the excellent reproducer. It would seem like the issue was introduced in 26.1. I've yet to identify what exactly it is that is going wrong but I suspect that it may be #7473 that is causing the problem.

**Comment by garazdawi** [comment]
Fix available in #7892, when the Windows installer has been built it would be great if you could install and test the fix to see if it solves the original problem and not only the reproducer.

**Comment by lukaszsamson** [comment]
@garazdawi the build from #7892 is completely broken. I'm unable to test anything as ElixirLS launch script hangs on my machine (Win 11). You can reproduce that with elixir 1.15.7 iex
```
Mix.install([:jason])
```
```
Erlang/OTP 27 [DEVELOPMENT] [erts-14.1.1] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.15.7) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Mix.install([:jason])

12:51:06.220 [error] beam\beam_load.c(607): Error loading function 'Elixir.Hex.Netrc.Cache':fetch/1: op make_fun2 u:
  no specific operation found
```

**Comment by garazdawi** [comment]
Ah, yes of course. `mix` downloads a precompiled hex archive that is built using an Erlang compiler that is no longer supported by Erlang/OTP 27 which is what the PR builds.

You should be able to use the installer found in my repo: https://github.com/garazdawi/otp/actions/runs/6934164812

Look for the artifact called [otp_win32_installer](https://github.com/garazdawi/otp/suites/18351298429/artifacts/1062301918).

**Comment by lukaszsamson** [comment]
@garazdawi OK, I tried your build and and I can't reproduce the bug anymore

**Comment by garazdawi** [comment]
Great! Thanks again for excellent reproducer!
