### ISSUE TITLE
ERL-155: R19-rc2 compilation error on FreeBSD 10.3-p4 in unix_efile

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#3071]
Original reporter: `gsmith`
Affected version: `OTP-19.0`
Fixed in version: `OTP-19.0`
Component: `erts`
Migrated from: https://bugs.erlang.org/browse/ERL-155

---

```
Going back, this error was present in rc1 as well.
I'm on FreeBSD 10.3-p4, trying to compile with both GCC 4.8 and clang
3.4.  I get the same error with both compilers

compile command (clang)

./otp_build setup -a --prefix=/home/gsmith
--with-wx-config=/usr/local/bin/wxgtk2u-3.0-config

compile command (gcc)

env CC=gcc48 CXX=g++48 ./otp_build setup -a --prefix=/home/gsmith
--with-wx-config=/usr/local/bin/wxgtk2u-3.0-config

error message:

In file included from beam/sys.h:105:0,
                 from drivers/unix/unix_efile.c:32:
sys/unix/erl_unix_sys.h: In function 'erts_check_fpe_thorough':
sys/unix/erl_unix_sys.h:424:5: error: implicit declaration of function
'finite' [-Werror=implicit-function-declaration]
     return erts_check_fpe(fp_exception, f) || !isfinite(f);
     ^
In file included from beam/erl_threads.h:268:0,
                 from beam/erl_smp.h:28,
                 from beam/sys.h:467,
                 from drivers/unix/unix_efile.c:32:
beam/erl_term.h: At top level:
beam/erl_term.h:57:8: error: #error Hipe on 64-bit needs a real mmap
as it does not support the literal tag
 #      error Hipe on 64-bit needs a real mmap as it does not support
the literal tag
        ^
cc1: some warnings being treated as errors
x86_64-unknown-freebsd10.3/Makefile:697: recipe for target
'obj/x86_64-unknown-freebsd10.3/opt/smp/unix_efile.o' failed

I'll be happy to assist in testing out patches if necessary.
```
