### PR TITLE
Fix regressions in code:ensure_loaded/1

### LINKED ISSUE #7725: code:ensure_loaded/1 hangs on case-mistaken module
**Describe the bug**
`code:ensure_loaded/1` hangs on the second call when the module has a case mistake on MacOS.

**To Reproduce**

With a `'Elixir.Foo'` module defined below, in `erl`:

```erlang
1> code:ensure_loaded('Elixir.FOo').
=ERROR REPORT==== 9-Oct-2023::08:18:48.125215 ===
beam/beam_load.c(180): Error loading module 'Elixir.FOo':
  module name in object code is 'Elixir.Foo'


{error,badfile}
2> code:ensure_loaded('Elixir.FOo').
% ===== hangs forever ====
```

**Expected behavior**

**Affected versions**
OTP 26.1 (works fine on 26.0.2).

**Additional context**

`cat Elixir.Foo.erl`:
```erlang
-module('Elixir.Foo').

-export([bar/0]).

bar() -> bar.
```

### PR DESCRIPTION
**Pull request by josevalim**
The first regression is not attempt to
load code if mode is embedded.

Erlang/OTP 25 only attempted to perform
code loading if the mode was interactive:

https://github.com/erlang/otp/blob/maint-25/lib/kernel/src/code_server.erl#L301

This check was removed in #6736 as part of
the decentralization. However, we received
reports of increased cpu/memory usage in
Erlang/OTP 26.1 in a code that was calling
code:ensure_loaded/1 on a hot path. The
underlying code was fixed but, given #7503
added the server back into the equation for
ensure_loaded we can add the mode check
back to preserve Erlang/OTP 25 behaviour.

The second regression would cause the caller
process to deadlock if attempting to load a
file with invalid .beam more than once.

Closes #7721.
Closes #7725.

### CODE REVIEW

**Review by jhogberg — APPROVED** [review]
Thanks for the PR! I've added it to our nightly runs.

File: lib/kernel/src/code_server.erl [hunk 1]
```diff
@@ -1409,7 +1405,7 @@ handle_on_load(Res, Action, _, _, St) ->
 handle_pending_on_load(Action, Mod, From, #state{on_load=OnLoad0}=St) ->
     case lists:keyfind(Mod, 2, OnLoad0) of
 	false ->
-	    Action(ok, St);
+	    Action({module, Mod}, St);
 	{{From,_Ref},Mod,_Pids} ->
 	    %% The on_load function tried to make an external
 	    %% call to its own module. That would be a deadlock.
```
Comment (michalmuskala) [inline lib/kernel/src/code_server.erl:1411]: I think in this case it still won't work correctly - this bypasses the call to `reply_loading` and just returns `reply` tuple directly.
Should this branch be changed to call `Action({error, deadlock}, St)` instead?

Comment (josevalim) [reply lib/kernel/src/code_server.erl:1411]: I could not run into this branch in my tests. It is either called if there is no waiting list (and then a single reply is fine) or skipped altogether if there is a waiting list. It also felt inaccurate to return `{error, deadlock}`. It probably makes sense only for the caller itself and the others should still see it as nofile/badfile?

Comment (michalmuskala) [reply lib/kernel/src/code_server.erl:1411]: My understanding is that it could trigger for an `on_load` function that is slow & recursive. I can generate a hanging situation with code like:+
```
-module(slow_on_load).

-on_load(on_load/0).

on_load() ->
    timer:sleep(1000),
    slow_on_load:foo().

foo() -> ok.
```

and calling `spawn(fun() -> code:ensure_loaded(slow_on_load) end), code:ensure_loaded(slow_on_load).` from the shell.
This is with code from this PR checked out.

Comment (josevalim) [reply lib/kernel/src/code_server.erl:1411]: Unfortunately, the error is not happening on this line of code. In your code, we never get to this clause, because we are stuck on loading the module.

I have a fix for this, but it is a bigger change, and I am not sure how comfortable I am in adding it to maint. My suggestion is to merge this into maint.

To recap:

1. If you have a deadlock inside an on_load callback by calling yourself, it will no longer go detected (it will effectively deadlock)
2. While this is a regression, previously deadlocking code would most likely fail anyway, so this regression is unlikely to break any actual code.
3. We should merge this PR into maint.
4. I will send another PR later which the team can evaluate if they want to bring into maint or not.

Comment (josevalim) [reply lib/kernel/src/code_server.erl:1410]: Of course, as soon as I wrote the above, I found a clean solution to the problem. I just had to move the `handle_pending_on_load` call up. I pushed a new commit for easier review, I'd be glad to squash or submit an additional PR. :)

**Review by michalmuskala — APPROVED** [review]

**Comment by jhogberg** [comment]
Some of our full nightly builds prior to your latest commit got stuck, which wasn't caught by the smoke tests here on GH nor the quick CI runs we do internally.

We've pulled it out of the nightly runs and are going to see if our newfangled `full-build-and-check` thing catches it. Otherwise I'll add it back to the ordinary runs tomorrow to see if your latest commit fixed it. :)

**Comment by jhogberg** [comment]
Still hangs in our nightly builds, roughly here:

```
02305: erlc -W  -Werror +debug_info -Werror -I../include -pa ../ebin -o../ebin application.erl
02306: erlc -W  -Werror +debug_info -Werror -I../include -pa ../ebin -o../ebin application_controller.erl
02307: erlc -W  -Werror +debug_info -Werror -I../include -pa ../ebin -o../ebin application_master.erl
02308: erlc -W  -Werror +debug_info -Werror -I../include -pa ../ebin -o../ebin application_starter.erl
02309: erlc -W  -Werror +debug_info -Werror -I../include -pa ../ebin -o../ebin auth.erl
02310: erlc -W  -Werror +debug_info -Werror -I../include -pa ../ebin -o../ebin code.erl
02311: erlc -W  -Werror +debug_info -Werror -I../include -pa ../ebin -o../ebin code_server.erl
```

**Comment by josevalim** [comment]
Thanks, I will investigate!

image

**Comment by josevalim** [comment]
@jhogberg do you have any suggestions on how to trigger it? Here is the code I have:

```
export ERL_TOP=$PWD
export PATH=$ERL_TOP/bin:$PATH
 ./otp_build all -a && ./otp_build tests
```

**Comment by jhogberg** [comment]
The commands as listed look a bit suspicious, with `-pa` and `-o` pointing at the same folder. That it also happens to be `code`/`code_server` it's hanging on is also a bit iffy. Perhaps just trying the commands as-they-are from the source folder might reproduce it?

```
02311: erlc -W  -Werror +debug_info -Werror -I../include -pa ../ebin -o../ebin code_server.erl
```

(This hasn't affected all of our machines, just a lot of them.)

**Comment by josevalim** [comment]
I had command running in a loop here, over 1000 iterations, and nothing. Do you know if, by the time this command runs, `lib/kernel` has already been bootstrapped? I assume so, because `erlc` cannot run without a code server? Or is there some bootstrap file we also need to update? Is ERLC_SERVER=true? If so, does it reload modules after they are compiled?

**Comment by jhogberg** [comment]
> Do you know if, by the time this command runs, lib/kernel has already been bootstrapped?

Yes, we're running with the bootstrap compiler. I find it strange that the build script explicitly includes the `ebin` it's building into though, I'll have to dig deeper.

> Is ERLC_SERVER=true?

No, I don't think so.

> If so, does it reload modules after they are compiled?

No, but there may be some parallelism going on, if one of these invocations yanks `code_server` just as another is trying to compile it, perhaps that could cause it?

**Comment by josevalim** [comment]
It could possibly be parallelism, since the Erlang compiler does remove the .beam file before starting, but I am wondering why this never happened before. Maybe we should try building with this line commented out just in case?

https://github.com/erlang/otp/blob/master/lib/compiler/src/compile.erl#L601

**Comment by josevalim** [comment]
Although I am looking at init.erl and it would fail to boot if `code` or `code_server` cannot be found...

**Comment by josevalim** [comment]
Ok, here is a more likely scenario: `code_server` is using functions from the `maps` module but the `maps` module is not preloaded. We should likely add `maps` to the preload list, could this be it?

**Comment by jhogberg** [comment]
> Although I am looking at init.erl and it would fail to boot if `code` or `code_server` cannot be found...

... but it will be found, I think we've nailed the problem here. Until the module has been compiled, the version present in the bootstrap folder will be used, but once a module has been compiled, that one will be loaded instead.

When `code` and `code_server` are out of sync, it may hang forever waiting for a reply that never arrives. I'm guessing that we haven't seen the issue before since the protocol doesn't change very often. This would also explain why not all builds hang, as another `erlc` would need to be started in the short window where `code` and `code_server` disagree.

I still need to look into why the `-pa ../ebin` slug gets added, it's super-strange.

**Comment by josevalim** [comment]
> This would also explain why not all builds hang, as another erlc would need to be started in the short window where code and code_server disagree.

What is weird is why we don't have failures caused by the very brief period of time where `code` or `code_server` are missing altogether because the compiler removed it?

Anyway, if this is the root cause, wouldn't updating the bootstrap files be enough to fix it?

**Comment by jhogberg** [comment]
> > This would also explain why not all builds hang, as another erlc would need to be started in the short window where code and code_server disagree.
> 
> What is weird is why we don't have failures caused by the very brief period of time where `code` or `code_server` are missing altogether because the compiler removed it?

They exist in the bootstrap `ebin` folder. `-pa ../ebin` ensures that `../ebin` gets checked first, it doesn't remove the bootstrap from the equation.

> Anyway, if this is the root cause, wouldn't updating the bootstrap files be enough to fix it?

Yeah, it should. I discussed it with @garazdawi and we think the proper solution is to remove the `-pa ../ebin` line from the `kernel` makefile (see https://github.com/erlang/otp/commit/2afd6748f16ad226d0ae12b54e57e0147dafdbdd#diff-d1dec6c42437980527c6df713899abe1af4ee1acfbbf074cb8eda0220f85eca8), and then update primary bootstrap.

**Comment by josevalim** [comment]
> Yeah, it should. I discussed it with @garazdawi and we think the proper solution is to remove the -pa ../ebin line from the kernel makefile (see https://github.com/erlang/otp/commit/2afd6748f16ad226d0ae12b54e57e0147dafdbdd#diff-d1dec6c42437980527c6df713899abe1af4ee1acfbbf074cb8eda0220f85eca8), and then update primary bootstrap.

Just to be clear, do you want me to make such changes, or will they be done separate and there will be another attempt to merge this PR?

At the moment, Elixir cannot run tests on OTP 26.1, as we test what happens when we fail to load modules, which currently triggers a deadlock. So it would be nice to address this as for OTP 26.2. :)

**Comment by jhogberg** [comment]
> Just to be clear, do you want me to make such changes, or will they be done separate and there will be another attempt to merge this PR?

Fixing it in this PR would be much appreciated, but if you lack the time I'll try to open a PR before Christmas. :)

**Comment by josevalim** [comment]
PR sent here: https://github.com/erlang/otp/pull/7949

**Comment by jhogberg** [comment]
Merged, thanks again for the PR! :)
