### PR TITLE
github: Disable iOS build as it fails to compile zlib

### PR DESCRIPTION
**Pull request by sverker**
Started to fail since zlib was updated in 7b9f48ac86cf589447d228aebde9d316bb692861.

`zlib/zconf.h:450:5: error: 'HAVE_STDARG_H' is not defined, evaluates to 0 [-Werror,-Wundef]`

@dominicletz

### CODE REVIEW

**Comment by sverker** [comment]
That compile error will happen when building with

`./configure --enable-builtin-zlib`

or on a system without a `zlib.h` available, I guess.

I will fix.

**Comment by sverker** [comment]
@dominicletz iOS build put back again by #10779
