### ISSUE TITLE
ERL-618: crypto does not build with libressl 2.7.2

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#3416]
Original reporter: `ci42`
Affected version: `Not Specified`
Fixed in versions: `OTP-20.3.6`, `OTP-21.0`
Component: `Not Specified`
Migrated from: https://bugs.erlang.org/browse/ERL-618

---

```
From the build log:

{noformat}
crypto.c:279:18: error: static declaration of 'HMAC_CTX_new' follows non-static declaration
static HMAC_CTX *HMAC_CTX_new(void);
                 ^
/opt/local/include/openssl/hmac.h:86:11: note: previous declaration is here
HMAC_CTX *HMAC_CTX_new(void);
          ^
crypto.c:280:13: error: static declaration of 'HMAC_CTX_free' follows non-static declaration
static void HMAC_CTX_free(HMAC_CTX *ctx);
            ^
/opt/local/include/openssl/hmac.h:87:6: note: previous declaration is here
void HMAC_CTX_free(HMAC_CTX *ctx);
     ^
crypto.c:282:18: error: static declaration of 'HMAC_CTX_new' follows non-static declaration
static HMAC_CTX *HMAC_CTX_new()
                 ^
/opt/local/include/openssl/hmac.h:86:11: note: previous declaration is here
HMAC_CTX *HMAC_CTX_new(void);
          ^
crypto.c:289:13: error: static declaration of 'HMAC_CTX_free' follows non-static declaration
static void HMAC_CTX_free(HMAC_CTX *ctx)
            ^
/opt/local/include/openssl/hmac.h:87:6: note: previous declaration is here
void HMAC_CTX_free(HMAC_CTX *ctx);
     ^
crypto.c:298:21: error: static declaration of 'BN_GENCB_get_arg' follows non-static declaration
static INLINE void *BN_GENCB_get_arg(BN_GENCB *cb);
                    ^
/opt/local/include/openssl/bn.h:291:7: note: previous declaration is here
void *BN_GENCB_get_arg(BN_GENCB *cb);
      ^
crypto.c:300:21: error: static declaration of 'BN_GENCB_get_arg' follows non-static declaration
static INLINE void *BN_GENCB_get_arg(BN_GENCB *cb)
                    ^
/opt/local/include/openssl/bn.h:291:7: note: previous declaration is here
void *BN_GENCB_get_arg(BN_GENCB *cb);
      ^
crypto.c:305:19: error: static declaration of 'RSA_set0_key' follows non-static declaration
static INLINE int RSA_set0_key(RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d);
                  ^
/opt/local/include/openssl/rsa.h:401:5: note: previous declaration is here
int RSA_set0_key(RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d);
    ^
crypto.c:306:20: error: static declaration of 'RSA_get0_key' follows non-static declaration
static INLINE void RSA_get0_key(const RSA *r, const BIGNUM **n, const BIGNUM **e, const BIGNUM **d);
                   ^
/opt/local/include/openssl/rsa.h:399:6: note: previous declaration is here
void RSA_get0_key(const RSA *r, const BIGNUM **n, const BIGNUM **e,
     ^
crypto.c:307:19: error: static declaration of 'RSA_set0_factors' follows non-static declaration
static INLINE int RSA_set0_factors(RSA *r, BIGNUM *p, BIGNUM *q);
                  ^
/opt/local/include/openssl/rsa.h:406:5: note: previous declaration is here
int RSA_set0_factors(RSA *r, BIGNUM *p, BIGNUM *q);
    ^
crypto.c:308:20: error: static declaration of 'RSA_get0_factors' follows non-static declaration
static INLINE void RSA_get0_factors(const RSA *r, const BIGNUM **p, const BIGNUM **q);
                   ^
/opt/local/include/openssl/rsa.h:405:6: note: previous declaration is here
void RSA_get0_factors(const RSA *r, const BIGNUM **p, const BIGNUM **q);
     ^
crypto.c:309:19: error: static declaration of 'RSA_set0_crt_params' follows non-static declaration
static INLINE int RSA_set0_crt_params(RSA *r, BIGNUM *dmp1, BIGNUM *dmq1, BIGNUM *iqmp);
                  ^
/opt/local/include/openssl/rsa.h:404:5: note: previous declaration is here
int RSA_set0_crt_params(RSA *r, BIGNUM *dmp1, BIGNUM *dmq1, BIGNUM *iqmp);
    ^
crypto.c:310:20: error: static declaration of 'RSA_get0_crt_params' follows non-static declaration
static INLINE void RSA_get0_crt_params(const RSA *r, const BIGNUM **dmp1, const BIGNUM **dmq1, const BIGNUM **iqmp);
                   ^
/opt/local/include/openssl/rsa.h:402:6: note: previous declaration is here
void RSA_get0_crt_params(const RSA *r, const BIGNUM **dmp1, const BIGNUM **dmq1,
     ^
crypto.c:312:19: error: static declaration of 'RSA_set0_key' follows non-static declaration
static INLINE int RSA_set0_key(RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d)
                  ^
/opt/local/include/openssl/rsa.h:401:5: note: previous declaration is here
int RSA_set0_key(RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d);
    ^
crypto.c:320:20: error: static declaration of 'RSA_get0_key' follows non-static declaration
static INLINE void RSA_get0_key(const RSA *r, const BIGNUM **n, const BIGNUM **e, const BIGNUM **d)
                   ^
/opt/local/include/openssl/rsa.h:399:6: note: previous declaration is here
void RSA_get0_key(const RSA *r, const BIGNUM **n, const BIGNUM **e,
     ^
crypto.c:327:19: error: static declaration of 'RSA_set0_factors' follows non-static declaration
static INLINE int RSA_set0_factors(RSA *r, BIGNUM *p, BIGNUM *q)
                  ^
/opt/local/include/openssl/rsa.h:406:5: note: previous declaration is here
int RSA_set0_factors(RSA *r, BIGNUM *p, BIGNUM *q);
    ^
crypto.c:334:20: error: static declaration of 'RSA_get0_factors' follows non-static declaration
static INLINE void RSA_get0_factors(const RSA *r, const BIGNUM **p, const BIGNUM **q)
                   ^
/opt/local/include/openssl/rsa.h:405:6: note: previous declaration is here
void RSA_get0_factors(const RSA *r, const BIGNUM **p, const BIGNUM **q);
     ^
crypto.c:340:19: error: static declaration of 'RSA_set0_crt_params' follows non-static declaration
static INLINE int RSA_set0_crt_params(RSA *r, BIGNUM *dmp1, BIGNUM *dmq1, BIGNUM *iqmp)
                  ^
/opt/local/include/openssl/rsa.h:404:5: note: previous declaration is here
int RSA_set0_crt_params(RSA *r, BIGNUM *dmp1, BIGNUM *dmq1, BIGNUM *iqmp);
    ^
crypto.c:348:20: error: static declaration of 'RSA_get0_crt_params' follows non-static declaration
static INLINE void RSA_get0_crt_params(const RSA *r, const BIGNUM **dmp1, const BIGNUM **dmq1, const BIGNUM **iqmp)
                   ^
/opt/local/include/openssl/rsa.h:402:6: note: previous declaration is here
void RSA_get0_crt_params(const RSA *r, const BIGNUM **dmp1, const BIGNUM **dmq1,
     ^
crypto.c:355:19: error: static declaration of 'DSA_set0_key' follows non-static declaration
static INLINE int DSA_set0_key(DSA *d, BIGNUM *pub_key, BIGNUM *priv_key);
                  ^
/opt/local/include/openssl/dsa.h:266:5: note: previous declaration is here
int DSA_set0_key(DSA *d, BIGNUM *pub_key, BIGNUM *priv_key);
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

{noformat}

See https://trac.macports.org/ticket/56394
```
