### ISSUE TITLE
wxWidgets variant does not build with wxGTK-3.0

### ISSUE THREAD

**Issue by barracuda156** [erlang/otp#8370]
**Describe the bug**
Trying to build Erlang with wxWidgets support via wxGTK-3.0 fails.

**To Reproduce**
Run the build, get:
```
 CXX	powerpc-apple-darwin10.0.0d2/wxe_impl.o
wxe_impl.cpp: In member function ‘virtual bool WxeApp::OnInit()’:
wxe_impl.cpp:204: error: ‘MacSetCommonMenuBar’ is not a member of ‘wxMenuBar’
wxe_impl.cpp:205: error: ‘class wxMenuBar’ has no member named ‘MacInstallMenuBar’
make[3]: *** [powerpc-apple-darwin10.0.0d2/wxe_impl.o] Error 1
```
It looks like it is hardcoded to expect Cocoa.

**Expected behavior**
It is desirable to have it supported, since Cocoa version of wxWidgets 3.x is broken on a number of macOS versions (3.2 does not build on many, 3.0 builds but does not work correctly on < 10.9 or so).

**Affected versions**
26.2.3

**Additional context**
Macports build system.

**Comment by barracuda156** [comment]
Commenting out that chunk in `wxe_impl.cpp` lets build proceed, but then it fails on:
```
Undefined symbols:
  ".objc_class_name_NSAutoreleasePool", referenced from:
      literal-pointer@__OBJC@__cls_refs@NSAutoreleasePool in wxe_ps_init.o
  ".objc_class_name_NSImage", referenced from:
      literal-pointer@__OBJC@__cls_refs@NSImage in wxe_ps_init.o
  "_NSApp", referenced from:
      _NSApp$non_lazy_ptr in wxe_ps_init.o
  ".objc_class_name_NSMutableString", referenced from:
      literal-pointer@__OBJC@__cls_refs@NSMutableString in wxe_ps_init.o
  ".objc_class_name_NSRunningApplication", referenced from:
      literal-pointer@__OBJC@__cls_refs@NSRunningApplication in wxe_ps_init.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
```
Perhaps just macros are currently wrong, and all those `#ifdef _MACOSX` should not be used on macOS with wxGTK.

**Comment by barracuda156** [comment]
BTW, I guess https://github.com/erlang/otp/commit/46320cb4a91664f56e9522260ad112435a463bab commit refers to a bug in wxWidgets 3.0 due to which they are broken, but the problem is that later versions are broken completely, i.e. not able to build.

**Comment by dgud** [comment]
I'll not work on this send a PR if you want this supported.
